### ISSUE TITLE
500 error getting comments

### ISSUE THREAD

**Issue by dsharpe** [everwin-sx/sx-api#2]
When I run this command: `CommentList commentList = candidatesService.queryComments(candidate.getId(), null);`

The following error is returned:
fr.everwin.open.api.exception.RequestException: Message : Property 'cucGrp' not found in class comnt
Error code : 5001
Status : 500
Developer message : SYSTEM [101] : Property not found : Property 'cucGrp' not found in class comnt

I was able to reproduce this on the companyService as well. Is there perhaps a new field in the XML that has not been added to the Java class?

**Comment by dsharpe** [comment]
@everwin-team please help! :)

**Comment by everwin-team** [comment]
The error seems to be an error on the SX application not on the client API, please contact everwin support to see in logs what's going wrong.
