### ISSUE TITLE
Pull Request - Download reports

### ISSUE THREAD

**Issue by Whoisnicko** [everwin-sx/sx-api#8]
It would be awesome to have a code to download a report from an already existing filtered query.

**Comment by everwin-team** [comment]
Can you give us an example ?

**Comment by Whoisnicko** [comment]
Sure, see an example below:

As you might be aware of, you create a specific filter and bookmark it to export reports in Excel format.

![image](https://user-images.githubusercontent.com/85567161/158250965-40bf26bc-f8a5-46ff-a41a-4cc38d20c0bc.png)

What I'd like to have is a pull request to use a specific bookmark to get the downloaded report automatically.

**Comment by everwin-team** [comment]
This is a new feature for the SX API not for the API's client. This feature will be push to the R&D.
